import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { compileFromFile } from 'json-schema-to-typescript';

const root = path.resolve(import.meta.dirname, '..');
const schemaDir = path.join(root, 'schemas');
const outputPath = path.join(root, 'generated', 'types.ts');

const schemaFiles = [
  ['entity', 'entity.schema.json'],
  ['object', 'object.schema.json'],
  ['task', 'task.schema.json'],
  ['observation', 'observation.schema.json'],
  ['commandCatalog', 'command-catalog.schema.json'],
  ['changeEvent', 'change-event.schema.json'],
  ['validationError', 'validation-error.schema.json'],
] as const;

const header = `/* eslint-disable */\n/* generated by scripts/generate-types.ts */\n\n`;

const blocks: string[] = [];
for (const [name, file] of schemaFiles) {
  blocks.push(await compileFromFile(path.join(schemaDir, file), { bannerComment: '', cwd: schemaDir, title: name }));
}

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${header}${blocks.join('\n\n')}`);
