import fs from "fs";
import path from "path";
import { buildSchemaBundleJSON } from "./schema-bundle-builder";
import { resolveAtlasProtocolPackageRoot } from "./path-utils";

const goEmbedFile = `// Code generated by atlas-protocol; DO NOT EDIT.

package protocol

import _ "embed"

//go:embed generated/schema_bundle.json
var schemaBundleJSON []byte
`;

function main(): void {
  const args = process.argv.slice(2);
  const checkOnly = args.includes("--check");

  try {
    const atlasProtocolRoot = resolveAtlasProtocolPackageRoot();
    const bundleText = buildSchemaBundleJSON(atlasProtocolRoot);
    const goDir = path.join(atlasProtocolRoot, "packages", "go");
    const jsonPath = path.join(goDir, "generated", "schema_bundle.json");
    const goPath = path.join(goDir, "schema_bundle_generated.go");

    if (checkOnly) {
      let diskJson: string;
      let diskGo: string;
      try {
        diskJson = fs.readFileSync(jsonPath, "utf8");
        diskGo = fs.readFileSync(goPath, "utf8");
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`[atlas-protocol] generate-go --check failed: ${message}`);
        process.exit(1);
      }
      if (diskJson !== bundleText) {
        console.error(
          `[atlas-protocol] generate-go --check: ${jsonPath} is stale (run npm run build to regenerate)`,
        );
        process.exit(1);
      }
      if (diskGo !== goEmbedFile) {
        console.error(
          `[atlas-protocol] generate-go --check: ${goPath} is stale (run npm run build to regenerate)`,
        );
        process.exit(1);
      }
      console.log("[atlas-protocol] generate-go --check passed");
      return;
    }

    fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
    fs.writeFileSync(jsonPath, bundleText);
    fs.writeFileSync(goPath, goEmbedFile);
    console.log(`[atlas-protocol] wrote ${jsonPath}`);
    console.log(`[atlas-protocol] wrote ${goPath}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`[atlas-protocol] generate-go failed: ${message}`);
    process.exit(1);
  }
}

main();
