import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { compileFromFile } from 'json-schema-to-typescript';

const root = path.resolve(import.meta.dirname, '..');
const schemaDir = path.join(root, 'schemas');
const outputPath = path.join(root, 'generated', 'types.ts');

const schemaFiles = [
  ['entity', 'entity.schema.json'],
  ['object', 'object.schema.json'],
  ['task', 'task.schema.json'],
  ['observation', 'observation.schema.json'],
  ['commandCatalog', 'command-catalog.schema.json'],
  ['changeEvent', 'change-event.schema.json'],
  ['validationError', 'validation-error.schema.json'],
] as const;

const header = `/* eslint-disable */\n/* generated by scripts/generate-types.ts */\n\n`;

function stripTrailingJsDoc(lines: string[]): void {
  while (lines.length > 0 && lines.at(-1)?.trim() === '') {
    lines.pop();
  }
  if (!lines.at(-1)?.trim().endsWith('*/')) {
    return;
  }
  while (lines.length > 0) {
    const line = lines.pop();
    if (line?.trim().startsWith('/**')) {
      break;
    }
  }
  while (lines.length > 0 && lines.at(-1)?.trim() === '') {
    lines.pop();
  }
}

function dedupeDeclarations(source: string): string {
  const seen = new Set<string>();
  const output: string[] = [];
  const pending: string[] = [];
  const lines = source.split('\n');
  let index = 0;

  while (index < lines.length) {
    const line = lines[index];
    const match = line.match(/^export (interface|type) (\w+)/);
    if (!match) {
      pending.push(line);
      index += 1;
      continue;
    }

    const kind = match[1];
    const name = match[2];
    const declaration = [line];
    let depth = (line.match(/{/g) ?? []).length - (line.match(/}/g) ?? []).length;
    index += 1;
    while (index < lines.length) {
      const current = lines[index];
      declaration.push(current);
      depth += (current.match(/{/g) ?? []).length - (current.match(/}/g) ?? []).length;
      index += 1;
      if (kind === 'interface' && depth <= 0) {
        break;
      }
      if (kind === 'type' && depth <= 0 && current.trim().endsWith(';')) {
        break;
      }
    }

    if (seen.has(name)) {
      stripTrailingJsDoc(pending);
      continue;
    }
    seen.add(name);
    output.push(...pending, ...declaration);
    pending.length = 0;
  }

  output.push(...pending);
  return `${output.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

function narrowCustomSectionPatternProperties(source: string): string {
  return source.replaceAll('[k: string]: CustomSection;', '[k: `custom_${string}`]: CustomSection;');
}

const blocks: string[] = [];
for (const [name, file] of schemaFiles) {
  blocks.push(await compileFromFile(path.join(schemaDir, file), { bannerComment: '', cwd: schemaDir, title: name }));
}

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${header}${narrowCustomSectionPatternProperties(dedupeDeclarations(blocks.join('\n\n')))}`);
